### ISSUE TITLE
client side electoral reg lookup 

### ISSUE THREAD

**Issue by sentinelweb** [TechForUK/simple-vote-ui#2]
after user enters postcode

https://wheredoivote.co.uk/api/beta/postcode/SW1A1AA.json

API docs https://wheredoivote.co.uk/api/#

**Comment by sentinelweb** [comment]
we need an api key to use over 1000 requests/day - I have emailed as per the API doc s page

**Comment by AugustinGrigorov** [comment]
This is now done
