### ISSUE TITLE
Postal vote questions UI suggestion

### ISSUE THREAD

**Issue by calroscow** [TechForUK/simple-vote-ui#23]
The options that appear for Postal Vote aren't very clear they relate to postal vote. Is it possible to indent these, so that they look like sub questions?
![Screenshot 2019-04-30 at 22 54 22](https://user-images.githubusercontent.com/50082157/56995971-22d50700-6b9b-11e9-8c8f-9e6e5cfd74c9.png)

Perhaps we could add "..." at the end of the postal vote question, and to the beginning of the options.

EXAMPLE

I would like to vote by postal vote...
      ...until further notice
      ...for elections to be held on a specific date
      ...for a period of time

**Comment by sentinelweb** [comment]
PR https://github.com/TechForUK/simple-vote-ui/pull/32
